Python
Traceback (most recent call last):
  File "/RIOT/dist/tools/dhcpv6-pd_ia/dhcpv6-pd_ia.py", line 72, in <module>
    main()
  File "/RIOT/dist/tools/dhcpv6-pd_ia/dhcpv6-pd_ia.py", line 68, in main
    server.run()
  File "/RIOT/dist/tools/dhcpv6-pd_ia/kea.py", line 110, in run
    self.install()
  File "/RIOT/dist/tools/dhcpv6-pd_ia/base.py", line 92, in install
    self.installer = pkg.PackageManagerFactory.get_installer()
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/RIOT/dist/tools/dhcpv6-pd_ia/pkg/__init__.py", line 50, in get_installer
    return AskToInstall()
           ^^^^^^^^^^^^^^
TypeError: Installer.__init__() missing 1 required positional argument: 'os'